### ISSUE TITLE
Error in ffmpeg command line

### ISSUE THREAD

**Issue by Saentist** [ponwork/multicast-checker#3]
```bash
# python3 multicast-checker.py --playlist output.m3u
  File "multicast-checker.py", line 47
    result = subprocess.run(['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_programs', f'udp://@{address}:{port}'], capture_output=True, text=True, timeout=args.info_timeout)
                                                                                                                           ^
SyntaxError: invalid syntax

```
OS Ubuntu 16.04 x64
Python 3.5.2
```shell
ffmpeg -version
ffmpeg version git-2019-04-04-8e3b01e Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 20160609
configuration: --pkg-config-flags=--static --prefix=/root/ffmpeg-build-static-binaries --bindir=/root/ffmpeg-build-static-binaries/bin --extra-cflags='-I /root/ffmpeg-build-static-binaries/include -I /usr/local/cuda/include/' --extra-ldflags='-L /root/ffmpeg-build-static-binaries/lib -L /usr/local/cuda/lib64/' --extra-libs=-lpthread --enable-cuda --enable-cuda-sdk --enable-cuvid --enable-libnpp --enable-gpl --enable-libass --enable-libfdk-aac --enable-vaapi --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-libaom --enable-nvenc
libavutil      56. 26.100 / 56. 26.100
libavcodec     58. 48.101 / 58. 48.101
libavformat    58. 26.101 / 58. 26.101
libavdevice    58.  7.100 / 58.  7.100
libavfilter     7. 48.100 /  7. 48.100
libswscale      5.  4.100 /  5.  4.100
libswresample   3.  4.100 /  3.  4.100
libpostproc    55.  4.100 / 55.  4.100

```

**Comment by ponwork** [comment]
> ```shell
> # python3 multicast-checker.py --playlist output.m3u
>   File "multicast-checker.py", line 47
>     result = subprocess.run(['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_programs', f'udp://@{address}:{port}'], capture_output=True, text=True, timeout=args.info_timeout)
>                                                                                                                            ^
> SyntaxError: invalid syntax
> ```
> 
> OS Ubuntu 16.04 x64
> Python 3.5.2
> 
> ```shell
> ffmpeg -version
> ffmpeg version git-2019-04-04-8e3b01e Copyright (c) 2000-2019 the FFmpeg developers
> built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 20160609
> configuration: --pkg-config-flags=--static --prefix=/root/ffmpeg-build-static-binaries --bindir=/root/ffmpeg-build-static-binaries/bin --extra-cflags='-I /root/ffmpeg-build-static-binaries/include -I /usr/local/cuda/include/' --extra-ldflags='-L /root/ffmpeg-build-static-binaries/lib -L /usr/local/cuda/lib64/' --extra-libs=-lpthread --enable-cuda --enable-cuda-sdk --enable-cuvid --enable-libnpp --enable-gpl --enable-libass --enable-libfdk-aac --enable-vaapi --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-libaom --enable-nvenc
> libavutil      56. 26.100 / 56. 26.100
> libavcodec     58. 48.101 / 58. 48.101
> libavformat    58. 26.101 / 58. 26.101
> libavdevice    58.  7.100 / 58.  7.100
> libavfilter     7. 48.100 /  7. 48.100
> libswscale      5.  4.100 /  5.  4.100
> libswresample   3.  4.100 /  3.  4.100
> libpostproc    55.  4.100 / 55.  4.100
> ```

Please [update](https://www.python.org/downloads/) your Python to at least ver. **3.6** where the "[F-strings](https://www.python.org/dev/peps/pep-0498/)" are supported.
