### ISSUE TITLE
Using on Raspbian

### ISSUE THREAD

**Issue by evandroamaro** [ponwork/multicast-checker#4]
Hi, 
I'm trying to use this on a Raspberry, with Raspbian. 
the multicast-checker indicates there's no multicasts. 

There's multicasts on the ethernet interface. Actually, this very Raspberry is multicasting one of them. 
I indicate the correct interface IP 
I use a playlist that works perfectly in VLC. 
I did change the regular expression code for the m3u parser, in order to get any order number. 
I added a some debug prints, I was in doubt if the socket was being created.

```
python3 ./multicast-checker.py --playlist ../PBT.canais_sample.m3u --nic 10.22.224.100
[*] Email parameters are not defined.
[*] Run the script with -h parameter for the details.

socket  <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=17, laddr=('10.22.224.100', 1234)>
socket  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=17, laddr=('10.22.224.100', 5501)>
socket  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=17, laddr=('10.22.224.100', 5501)>
address:  239.251.0.60  port:  5501 Resultado:  1
[*] Channel  24 Kitchen HD is not working
address:  239.192.1.203  port:  1234 Resultado:  1
address:  239.251.0.97  port:  5501 Resultado:  1
[*] Channel  Bay is not working
[*] Channel  AMC HD is not working

[*] The following channel(s) are not working:

239.251.0.60:5501 -  24 Kitchen HD
239.192.1.203:1234 -  Bay
239.251.0.97:5501 -  AMC HD


[*] Finished in 5.0 second(s)
```

Where one reads 
address: xxx.xxx.xxx.xxx port: xxxx Resultado: X
Is in mass_checker(channel), the result of channel_checker(sock)

```
def mass_checker(channel):
    # Function to mass check the channels in the dictionary

    # Define global variables
    global os_name
    global channels_not_working

    # Check channel
    channel_address, channel_port = channels_dictionary[channel].split(':')
    sock = socket_creator(args.nic, channel_address, channel_port, os_name)
    result = channel_checker(sock)
-> print('address: ', channel_address, ' port: ', channel_port, 'Resultado: ', result, sep=" ")
```

Raspbian is Debian based. So is Ubuntu. 
How can I further debug this? 
Might there be a difference in how sockets are created? Or a difference in how ffprobe is called in Raspbian?

**Comment by evandroamaro** [comment]
I made some advances comenting out the socket creation. 

I also added options to ffprobe udp://@{address}:{port}?{ffprobeOptions}
Namely ffprobeOptions = f'localaddr={args.nic}', which now works in finding streams.
But isn't stable. There's many streams in the playlist that it does not detect. But the next time I run they come up. And vice versa.

**Comment by ponwork** [comment]
@evandroamaro Hello

Thank you for the feedback.
First of all I am very pleased that you found my pet-project applicable for your task.

The code I've made was mainly focused to Russian ISP's IPTV streams and I had no chances to test it more widely.

If you can help me and somehow allow to perform the tests on the IPTV streams you have -- I will try to change the script respectively.

Regards

Yuri

**Comment by evandroamaro** [comment]
I increased the default timeout values and now all seems to be working great. 
So in summary I've changed:
 - Disable the socket creation
 - Add the localaddr option into ffprobe
 - Increase the timeout values up 3x, to allow enough time to receive all stream info. 
 
I will continue to validate but I think I have a working solution for Raspberry, at least for what I needed to do.

Thank you for your work.

**Comment by ponwork** [comment]
> I increased the default timeout values and now all seems to be working great.
> So in summary I've changed:
> 
> * Disable the socket creation
> * Add the localaddr option into ffprobe
> * Increase the timeout values up 3x, to allow enough time to receive all stream info.
> 
> I will continue to validate but I think I have a working solution for Raspberry, at least for what I needed to do.
> 
> Thank you for your work.

Hi @evandroamaro 
I am very appreciated that my code helped you!

Cheers!
